import type { Data } from 'react-svg-worldmap'

export const defaultMapData: Data<string> = [
  { country: 'dz', value: JSON.stringify({ name: 'Algeria', alpha3: 'DZA', color: '#F4A261' }) },
  { country: 'ao', value: JSON.stringify({ name: 'Angola', alpha3: 'AGO', color: '#E76F51' }) },
  { country: 'bj', value: JSON.stringify({ name: 'Benin', alpha3: 'BEN', color: '#FFBA08' }) },
  { country: 'bw', value: JSON.stringify({ name: 'Botswana', alpha3: 'BWA', color: '#FAA307' }) },
  {
    country: 'bf',
    value: JSON.stringify({ name: 'Burkina Faso', alpha3: 'BFA', color: '#E9C46A' }),
  },
  { country: 'bi', value: JSON.stringify({ name: 'Burundi', alpha3: 'BDI', color: '#F4D06F' }) },
  { country: 'cm', value: JSON.stringify({ name: 'Cameroon', alpha3: 'CMR', color: '#FCA311' }) },
  {
    country: 'cf',
    value: JSON.stringify({ name: 'Central African Rep.', alpha3: 'CAF', color: '#FFB703' }),
  },
  { country: 'td', value: JSON.stringify({ name: 'Chad', alpha3: 'TCD', color: '#FB8500' }) },
  { country: 'cg', value: JSON.stringify({ name: 'Congo', alpha3: 'COG', color: '#F3722C' }) },
  {
    country: 'ci',
    value: JSON.stringify({ name: "Côte d'Ivoire", alpha3: 'CIV', color: '#F4A261' }),
  },
  {
    country: 'cd',
    value: JSON.stringify({ name: 'Dem. Rep. Congo', alpha3: 'COD', color: '#E76F51' }),
  },
  { country: 'dj', value: JSON.stringify({ name: 'Djibouti', alpha3: 'DJI', color: '#FFBA08' }) },
  { country: 'eg', value: JSON.stringify({ name: 'Egypt', alpha3: 'EGY', color: '#FAA307' }) },
  { country: 'gq', value: JSON.stringify({ name: 'Eq. Guinea', alpha3: 'GNQ', color: '#E9C46A' }) },
  { country: 'er', value: JSON.stringify({ name: 'Eritrea', alpha3: 'ERI', color: '#F4D06F' }) },
  { country: 'sz', value: JSON.stringify({ name: 'eSwatini', alpha3: 'SWZ', color: '#FCA311' }) },
  { country: 'et', value: JSON.stringify({ name: 'Ethiopia', alpha3: 'ETH', color: '#FFB703' }) },
  { country: 'ga', value: JSON.stringify({ name: 'Gabon', alpha3: 'GAB', color: '#FB8500' }) },
  { country: 'gm', value: JSON.stringify({ name: 'Gambia', alpha3: 'GMB', color: '#F3722C' }) },
  { country: 'gh', value: JSON.stringify({ name: 'Ghana', alpha3: 'GHA', color: '#F4A261' }) },
  { country: 'gn', value: JSON.stringify({ name: 'Guinea', alpha3: 'GIN', color: '#E76F51' }) },
  {
    country: 'gw',
    value: JSON.stringify({ name: 'Guinea-Bissau', alpha3: 'GNB', color: '#FFBA08' }),
  },
  { country: 'ke', value: JSON.stringify({ name: 'Kenya', alpha3: 'KEN', color: '#FAA307' }) },
  { country: 'ls', value: JSON.stringify({ name: 'Lesotho', alpha3: 'LSO', color: '#E9C46A' }) },
  { country: 'lr', value: JSON.stringify({ name: 'Liberia', alpha3: 'LBR', color: '#F4D06F' }) },
  { country: 'ly', value: JSON.stringify({ name: 'Libya', alpha3: 'LBY', color: '#FCA311' }) },
  { country: 'mg', value: JSON.stringify({ name: 'Madagascar', alpha3: 'MDG', color: '#FFB703' }) },
  { country: 'mw', value: JSON.stringify({ name: 'Malawi', alpha3: 'MWI', color: '#FB8500' }) },
  { country: 'ml', value: JSON.stringify({ name: 'Mali', alpha3: 'MLI', color: '#F3722C' }) },
  { country: 'mr', value: JSON.stringify({ name: 'Mauritania', alpha3: 'MRT', color: '#F4A261' }) },
  { country: 'ma', value: JSON.stringify({ name: 'Morocco', alpha3: 'MAR', color: '#E76F51' }) },
  { country: 'mz', value: JSON.stringify({ name: 'Mozambique', alpha3: 'MOZ', color: '#FFBA08' }) },
  { country: 'na', value: JSON.stringify({ name: 'Namibia', alpha3: 'NAM', color: '#FAA307' }) },
  { country: 'ne', value: JSON.stringify({ name: 'Niger', alpha3: 'NER', color: '#E9C46A' }) },
  { country: 'ng', value: JSON.stringify({ name: 'Nigeria', alpha3: 'NGA', color: '#F4D06F' }) },
  { country: 'rw', value: JSON.stringify({ name: 'Rwanda', alpha3: 'RWA', color: '#FCA311' }) },
  { country: 'ss', value: JSON.stringify({ name: 'S. Sudan', alpha3: 'SDS', color: '#FFB703' }) },
  { country: 'sn', value: JSON.stringify({ name: 'Senegal', alpha3: 'SEN', color: '#FB8500' }) },
  {
    country: 'sl',
    value: JSON.stringify({ name: 'Sierra Leone', alpha3: 'SLE', color: '#F3722C' }),
  },
  { country: 'so', value: JSON.stringify({ name: 'Somalia', alpha3: 'SOM', color: '#F4A261' }) },
  {
    country: 'za',
    value: JSON.stringify({ name: 'South Africa', alpha3: 'ZAF', color: '#FFBA08' }),
  },
  { country: 'sd', value: JSON.stringify({ name: 'Sudan', alpha3: 'SDN', color: '#FAA307' }) },
  { country: 'tz', value: JSON.stringify({ name: 'Tanzania', alpha3: 'TZA', color: '#E9C46A' }) },
  { country: 'tg', value: JSON.stringify({ name: 'Togo', alpha3: 'TGO', color: '#F4D06F' }) },
  { country: 'tn', value: JSON.stringify({ name: 'Tunisia', alpha3: 'TUN', color: '#FCA311' }) },
  { country: 'ug', value: JSON.stringify({ name: 'Uganda', alpha3: 'UGA', color: '#FFB703' }) },
  { country: 'eh', value: JSON.stringify({ name: 'W. Sahara', alpha3: 'SAH', color: '#FB8500' }) },
  { country: 'zm', value: JSON.stringify({ name: 'Zambia', alpha3: 'ZMB', color: '#F3722C' }) },
  { country: 'zw', value: JSON.stringify({ name: 'Zimbabwe', alpha3: 'ZWE', color: '#F4A261' }) },
  { country: 'aq', value: JSON.stringify({ name: 'Antarctica', alpha3: 'ATA', color: '#B0BEC5' }) },
  {
    country: 'af',
    value: JSON.stringify({ name: 'Afghanistan', alpha3: 'AFG', color: '#2A9D8F' }),
  },
  { country: 'am', value: JSON.stringify({ name: 'Armenia', alpha3: 'ARM', color: '#38A3A5' }) },
  { country: 'az', value: JSON.stringify({ name: 'Azerbaijan', alpha3: 'AZE', color: '#22577A' }) },
  { country: 'bd', value: JSON.stringify({ name: 'Bangladesh', alpha3: 'BGD', color: '#57CC99' }) },
  { country: 'bt', value: JSON.stringify({ name: 'Bhutan', alpha3: 'BTN', color: '#80ED99' }) },
  { country: 'bn', value: JSON.stringify({ name: 'Brunei', alpha3: 'BRN', color: '#118AB2' }) },
  { country: 'kh', value: JSON.stringify({ name: 'Cambodia', alpha3: 'KHM', color: '#06D6A0' }) },
  { country: 'cn', value: JSON.stringify({ name: 'China', alpha3: 'CHN', color: '#40916C' }) },
  { country: 'cy', value: JSON.stringify({ name: 'Cyprus', alpha3: 'CYP', color: '#52B788' }) },
  { country: 'ge', value: JSON.stringify({ name: 'Georgia', alpha3: 'GEO', color: '#74C69D' }) },
  { country: 'in', value: JSON.stringify({ name: 'India', alpha3: 'IND', color: '#2A9D8F' }) },
  { country: 'id', value: JSON.stringify({ name: 'Indonesia', alpha3: 'IDN', color: '#38A3A5' }) },
  { country: 'ir', value: JSON.stringify({ name: 'Iran', alpha3: 'IRN', color: '#22577A' }) },
  { country: 'iq', value: JSON.stringify({ name: 'Iraq', alpha3: 'IRQ', color: '#57CC99' }) },
  { country: 'il', value: JSON.stringify({ name: 'Israel', alpha3: 'ISR', color: '#80ED99' }) },
  { country: 'jp', value: JSON.stringify({ name: 'Japan', alpha3: 'JPN', color: '#118AB2' }) },
  { country: 'jo', value: JSON.stringify({ name: 'Jordan', alpha3: 'JOR', color: '#06D6A0' }) },
  { country: 'kz', value: JSON.stringify({ name: 'Kazakhstan', alpha3: 'KAZ', color: '#40916C' }) },
  { country: 'kw', value: JSON.stringify({ name: 'Kuwait', alpha3: 'KWT', color: '#52B788' }) },
  { country: 'kg', value: JSON.stringify({ name: 'Kyrgyzstan', alpha3: 'KGZ', color: '#74C69D' }) },
  { country: 'la', value: JSON.stringify({ name: 'Laos', alpha3: 'LAO', color: '#2A9D8F' }) },
  { country: 'lb', value: JSON.stringify({ name: 'Lebanon', alpha3: 'LBN', color: '#38A3A5' }) },
  { country: 'my', value: JSON.stringify({ name: 'Malaysia', alpha3: 'MYS', color: '#22577A' }) },
  { country: 'mn', value: JSON.stringify({ name: 'Mongolia', alpha3: 'MNG', color: '#57CC99' }) },
  { country: 'mm', value: JSON.stringify({ name: 'Myanmar', alpha3: 'MMR', color: '#80ED99' }) },
  { country: 'np', value: JSON.stringify({ name: 'Nepal', alpha3: 'NPL', color: '#06D6A0' }) },
  {
    country: 'kp',
    value: JSON.stringify({ name: 'North Korea', alpha3: 'PRK', color: '#40916C' }),
  },
  { country: 'om', value: JSON.stringify({ name: 'Oman', alpha3: 'OMN', color: '#52B788' }) },
  { country: 'pk', value: JSON.stringify({ name: 'Pakistan', alpha3: 'PAK', color: '#74C69D' }) },
  { country: 'ps', value: JSON.stringify({ name: 'Palestine', alpha3: 'PSX', color: '#2A9D8F' }) },
  {
    country: 'ph',
    value: JSON.stringify({ name: 'Philippines', alpha3: 'PHL', color: '#38A3A5' }),
  },
  { country: 'qa', value: JSON.stringify({ name: 'Qatar', alpha3: 'QAT', color: '#22577A' }) },
  {
    country: 'sa',
    value: JSON.stringify({ name: 'Saudi Arabia', alpha3: 'SAU', color: '#57CC99' }),
  },
  {
    country: 'kr',
    value: JSON.stringify({ name: 'South Korea', alpha3: 'KOR', color: '#80ED99' }),
  },
  { country: 'lk', value: JSON.stringify({ name: 'Sri Lanka', alpha3: 'LKA', color: '#118AB2' }) },
  { country: 'sy', value: JSON.stringify({ name: 'Syria', alpha3: 'SYR', color: '#06D6A0' }) },
  { country: 'cn-tw', value: JSON.stringify({ name: 'Taiwan', alpha3: 'TWN', color: '#40916C' }) },
  { country: 'tj', value: JSON.stringify({ name: 'Tajikistan', alpha3: 'TJK', color: '#52B788' }) },
  { country: 'th', value: JSON.stringify({ name: 'Thailand', alpha3: 'THA', color: '#74C69D' }) },
  {
    country: 'tl',
    value: JSON.stringify({ name: 'Timor-Leste', alpha3: 'TLS', color: '#2A9D8F' }),
  },
  { country: 'tr', value: JSON.stringify({ name: 'Turkey', alpha3: 'TUR', color: '#38A3A5' }) },
  {
    country: 'tm',
    value: JSON.stringify({ name: 'Turkmenistan', alpha3: 'TKM', color: '#22577A' }),
  },
  {
    country: 'ae',
    value: JSON.stringify({ name: 'United Arab Emirates', alpha3: 'ARE', color: '#57CC99' }),
  },
  { country: 'uz', value: JSON.stringify({ name: 'Uzbekistan', alpha3: 'UZB', color: '#80ED99' }) },
  { country: 'vn', value: JSON.stringify({ name: 'Vietnam', alpha3: 'VNM', color: '#118AB2' }) },
  { country: 'ye', value: JSON.stringify({ name: 'Yemen', alpha3: 'YEM', color: '#06D6A0' }) },
  { country: 'al', value: JSON.stringify({ name: 'Albania', alpha3: 'ALB', color: '#4895EF' }) },
  { country: 'at', value: JSON.stringify({ name: 'Austria', alpha3: 'AUT', color: '#4361EE' }) },
  { country: 'by', value: JSON.stringify({ name: 'Belarus', alpha3: 'BLR', color: '#3F37C9' }) },
  { country: 'be', value: JSON.stringify({ name: 'Belgium', alpha3: 'BEL', color: '#7209B7' }) },
  {
    country: 'ba',
    value: JSON.stringify({ name: 'Bosnia and Herz.', alpha3: 'BIH', color: '#B5179E' }),
  },
  { country: 'bg', value: JSON.stringify({ name: 'Bulgaria', alpha3: 'BGR', color: '#9D4EDD' }) },
  { country: 'hr', value: JSON.stringify({ name: 'Croatia', alpha3: 'HRV', color: '#560BAD' }) },
  { country: 'cz', value: JSON.stringify({ name: 'Czechia', alpha3: 'CZE', color: '#5C6BC0' }) },
  { country: 'dk', value: JSON.stringify({ name: 'Denmark', alpha3: 'DNK', color: '#6979C4' }) },
  { country: 'ee', value: JSON.stringify({ name: 'Estonia', alpha3: 'EST', color: '#8590E4' }) },
  { country: 'fi', value: JSON.stringify({ name: 'Finland', alpha3: 'FIN', color: '#4895EF' }) },
  { country: 'de', value: JSON.stringify({ name: 'Germany', alpha3: 'DEU', color: '#3F37C9' }) },
  { country: 'gr', value: JSON.stringify({ name: 'Greece', alpha3: 'GRC', color: '#7209B7' }) },
  { country: 'hu', value: JSON.stringify({ name: 'Hungary', alpha3: 'HUN', color: '#B5179E' }) },
  { country: 'is', value: JSON.stringify({ name: 'Iceland', alpha3: 'ISL', color: '#9D4EDD' }) },
  { country: 'ie', value: JSON.stringify({ name: 'Ireland', alpha3: 'IRL', color: '#560BAD' }) },
  { country: 'it', value: JSON.stringify({ name: 'Italy', alpha3: 'ITA', color: '#5C6BC0' }) },
  { country: 'lv', value: JSON.stringify({ name: 'Latvia', alpha3: 'LVA', color: '#8590E4' }) },
  { country: 'lt', value: JSON.stringify({ name: 'Lithuania', alpha3: 'LTU', color: '#4895EF' }) },
  { country: 'lu', value: JSON.stringify({ name: 'Luxembourg', alpha3: 'LUX', color: '#4361EE' }) },
  { country: 'md', value: JSON.stringify({ name: 'Moldova', alpha3: 'MDA', color: '#3F37C9' }) },
  { country: 'me', value: JSON.stringify({ name: 'Montenegro', alpha3: 'MNE', color: '#7209B7' }) },
  {
    country: 'nl',
    value: JSON.stringify({ name: 'Netherlands', alpha3: 'NLD', color: '#B5179E' }),
  },
  {
    country: 'mk',
    value: JSON.stringify({ name: 'North Macedonia', alpha3: 'MKD', color: '#9D4EDD' }),
  },
  { country: 'pl', value: JSON.stringify({ name: 'Poland', alpha3: 'POL', color: '#5C6BC0' }) },
  { country: 'pt', value: JSON.stringify({ name: 'Portugal', alpha3: 'PRT', color: '#6979C4' }) },
  { country: 'ro', value: JSON.stringify({ name: 'Romania', alpha3: 'ROU', color: '#8590E4' }) },
  { country: 'ru', value: JSON.stringify({ name: 'Russia', alpha3: 'RUS', color: '#4895EF' }) },
  { country: 'rs', value: JSON.stringify({ name: 'Serbia', alpha3: 'SRB', color: '#4361EE' }) },
  { country: 'sk', value: JSON.stringify({ name: 'Slovakia', alpha3: 'SVK', color: '#3F37C9' }) },
  { country: 'si', value: JSON.stringify({ name: 'Slovenia', alpha3: 'SVN', color: '#7209B7' }) },
  { country: 'es', value: JSON.stringify({ name: 'Spain', alpha3: 'ESP', color: '#B5179E' }) },
  { country: 'se', value: JSON.stringify({ name: 'Sweden', alpha3: 'SWE', color: '#9D4EDD' }) },
  {
    country: 'ch',
    value: JSON.stringify({ name: 'Switzerland', alpha3: 'CHE', color: '#560BAD' }),
  },
  { country: 'ua', value: JSON.stringify({ name: 'Ukraine', alpha3: 'UKR', color: '#5C6BC0' }) },
  {
    country: 'gb',
    value: JSON.stringify({ name: 'United Kingdom', alpha3: 'GBR', color: '#6979C4' }),
  },
  { country: 'bs', value: JSON.stringify({ name: 'Bahamas', alpha3: 'BHS', color: '#EF476F' }) },
  { country: 'bz', value: JSON.stringify({ name: 'Belize', alpha3: 'BLZ', color: '#06D6A0' }) },
  { country: 'ca', value: JSON.stringify({ name: 'Canada', alpha3: 'CAN', color: '#118AB2' }) },
  { country: 'cr', value: JSON.stringify({ name: 'Costa Rica', alpha3: 'CRI', color: '#FFD166' }) },
  { country: 'cu', value: JSON.stringify({ name: 'Cuba', alpha3: 'CUB', color: '#E07A5F' }) },
  {
    country: 'do',
    value: JSON.stringify({ name: 'Dominican Rep.', alpha3: 'DOM', color: '#073B4C' }),
  },
  {
    country: 'sv',
    value: JSON.stringify({ name: 'El Salvador', alpha3: 'SLV', color: '#3D405B' }),
  },
  { country: 'gl', value: JSON.stringify({ name: 'Greenland', alpha3: 'GRL', color: '#81B29A' }) },
  { country: 'gt', value: JSON.stringify({ name: 'Guatemala', alpha3: 'GTM', color: '#F2CC8F' }) },
  { country: 'ht', value: JSON.stringify({ name: 'Haiti', alpha3: 'HTI', color: '#C77DFF' }) },
  { country: 'hn', value: JSON.stringify({ name: 'Honduras', alpha3: 'HND', color: '#EF476F' }) },
  { country: 'jm', value: JSON.stringify({ name: 'Jamaica', alpha3: 'JAM', color: '#06D6A0' }) },
  { country: 'mx', value: JSON.stringify({ name: 'Mexico', alpha3: 'MEX', color: '#118AB2' }) },
  { country: 'ni', value: JSON.stringify({ name: 'Nicaragua', alpha3: 'NIC', color: '#FFD166' }) },
  { country: 'pa', value: JSON.stringify({ name: 'Panama', alpha3: 'PAN', color: '#E07A5F' }) },
  {
    country: 'pr',
    value: JSON.stringify({ name: 'Puerto Rico', alpha3: 'PRI', color: '#073B4C' }),
  },
  {
    country: 'tt',
    value: JSON.stringify({ name: 'Trinidad and Tobago', alpha3: 'TTO', color: '#3D405B' }),
  },
  {
    country: 'us',
    value: JSON.stringify({ name: 'United States of America', alpha3: 'USA', color: '#81B29A' }),
  },
  { country: 'au', value: JSON.stringify({ name: 'Australia', alpha3: 'AUS', color: '#48CAE4' }) },
  { country: 'fj', value: JSON.stringify({ name: 'Fiji', alpha3: 'FJI', color: '#00B4D8' }) },
  {
    country: 'nc',
    value: JSON.stringify({ name: 'New Caledonia', alpha3: 'NCL', color: '#0096C7' }),
  },
  {
    country: 'nz',
    value: JSON.stringify({ name: 'New Zealand', alpha3: 'NZL', color: '#0077B6' }),
  },
  {
    country: 'pg',
    value: JSON.stringify({ name: 'Papua New Guinea', alpha3: 'PNG', color: '#023E8A' }),
  },
  {
    country: 'sb',
    value: JSON.stringify({ name: 'Solomon Is.', alpha3: 'SLB', color: '#ADE8F4' }),
  },
  { country: 'vu', value: JSON.stringify({ name: 'Vanuatu', alpha3: 'VUT', color: '#90E0EF' }) },
  {
    country: 'tf',
    value: JSON.stringify({ name: 'Fr. S. Antarctic Lands', alpha3: 'ATF', color: '#4a90d9' }),
  },
  { country: 'ar', value: JSON.stringify({ name: 'Argentina', alpha3: 'ARG', color: '#E63946' }) },
  { country: 'bo', value: JSON.stringify({ name: 'Bolivia', alpha3: 'BOL', color: '#F4A261' }) },
  { country: 'br', value: JSON.stringify({ name: 'Brazil', alpha3: 'BRA', color: '#A8DADC' }) },
  { country: 'cl', value: JSON.stringify({ name: 'Chile', alpha3: 'CHL', color: '#457B9D' }) },
  { country: 'co', value: JSON.stringify({ name: 'Colombia', alpha3: 'COL', color: '#1D3557' }) },
  { country: 'ec', value: JSON.stringify({ name: 'Ecuador', alpha3: 'ECU', color: '#FF6B6B' }) },
  {
    country: 'fk',
    value: JSON.stringify({ name: 'Falkland Is.', alpha3: 'FLK', color: '#E07A5F' }),
  },
  { country: 'gy', value: JSON.stringify({ name: 'Guyana', alpha3: 'GUY', color: '#3D405B' }) },
  { country: 'py', value: JSON.stringify({ name: 'Paraguay', alpha3: 'PRY', color: '#81B29A' }) },
  { country: 'pe', value: JSON.stringify({ name: 'Peru', alpha3: 'PER', color: '#F2CC8F' }) },
  { country: 'sr', value: JSON.stringify({ name: 'Suriname', alpha3: 'SUR', color: '#E63946' }) },
  { country: 'uy', value: JSON.stringify({ name: 'Uruguay', alpha3: 'URY', color: '#F4A261' }) },
  { country: 've', value: JSON.stringify({ name: 'Venezuela', alpha3: 'VEN', color: '#A8DADC' }) },
]
